[package]
name = "argon_fan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.15.*" }
signal-hook = "0.3.*"
sysinfo = "0.29.*"

[features]
mocki2c = []
