[package]
name = "argon_fan"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.18.*" }
signal-hook = "0.3.*"
sysinfo = "0.30.*"

[features]
mocki2c = []
